# Generated by Django 5.2.6 on 2025-09-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_oficial', models.CharField(max_length=150)),
                ('capital', models.CharField(blank=True, max_length=150, null=True)),
                ('regiao', models.CharField(max_length=50)),
                ('subregiao', models.CharField(blank=True, max_length=150, null=True)),
                ('populacao', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('idioma', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='paises.idioma')),
            ],
        ),
    ]
